//! The per-component behavior contract and the update context.

use crate::meta::ComponentDef;
use crate::value::{Changed, PropertyStore, Value};

/// An event delivered to a template `@event=${handler}` binding.
#[derive(Debug, Clone)]
pub struct UiEvent {
    /// Event name as bound in the template, e.g. `change`.
    pub name: String,
    /// The committed value of the event target, when the widget has one.
    pub target_value: Option<String>,
    /// The notify payload when the event is a child element's `*-changed`
    /// (the browser's `event.detail.value`).
    pub detail: Option<Value>,
}

impl UiEvent {
    pub fn change(target_value: impl Into<String>) -> Self {
        UiEvent {
            name: "change".to_string(),
            target_value: Some(target_value.into()),
            detail: None,
        }
    }

    /// A child element's notify event as seen by a parent template binding
    /// (`@value-changed=${handler}` on a nested custom element).
    pub fn notify(event: &NotifyEvent) -> Self {
        UiEvent {
            name: event.event_name.clone(),
            target_value: Some(event.value.display_text()),
            detail: Some(event.value.clone()),
        }
    }
}

/// A property-change notification, the `LitNotify` event analog.
#[derive(Debug, Clone, PartialEq)]
pub struct NotifyEvent {
    /// JavaScript property name, matching the browser event detail.
    pub property: String,
    /// Event name per the notify rules, e.g. `value-changed`.
    pub event_name: String,
    pub value: Value,
    pub old_value: Value,
}

/// Mutable view of an instance during lifecycle and handler calls.
/// Writes go through [`Ctx::set`] so the update cycle can collect the
/// [`Changed`] batch and emit notify events afterwards.
pub struct Ctx<'a> {
    store: &'a mut PropertyStore,
    changed: &'a mut Changed,
}

impl<'a> Ctx<'a> {
    pub fn new(store: &'a mut PropertyStore, changed: &'a mut Changed) -> Self {
        Ctx { store, changed }
    }

    pub fn get(&self, rust_name: &str) -> &Value {
        self.store.get(rust_name)
    }

    /// The property as text: the string's content, `""` for everything
    /// else — the common read of composite derivations.
    pub fn text(&self, rust_name: &str) -> String {
        self.store
            .get(rust_name)
            .as_str()
            .unwrap_or_default()
            .to_string()
    }

    /// Writes suppress equal values at the store: an unchanged property
    /// joins no batch, re-enters no `will_update` and notifies nobody —
    /// callers need no equality guard of their own.
    pub fn set(&mut self, rust_name: &'static str, value: impl Into<Value>) {
        if let Some(old) = self.store.set(rust_name, value) {
            self.changed.record(rust_name, old);
        }
    }
}

/// Component behavior for the TUI/native targets, mirroring the
/// HTMLElement/ReactiveElement lifecycle.
///
/// Implementations are generated by `#[derive(CustomElement)]`, which
/// dispatches to the per-component `<Name>Logic` trait.
pub trait Behavior: Send {
    fn def(&self) -> &'static ComponentDef;

    fn connected(&mut self, _ctx: &mut Ctx) {}

    fn disconnected(&mut self, _ctx: &mut Ctx) {}

    fn attribute_changed(
        &mut self,
        _ctx: &mut Ctx,
        _name: &str,
        _old: Option<&str>,
        _new: Option<&str>,
    ) {
    }

    /// Runs before render with the batch of changed properties;
    /// further [`Ctx::set`] calls join the same batch.
    fn will_update(&mut self, _ctx: &mut Ctx, _changed: &Changed) {}

    fn updated(&mut self, _ctx: &mut Ctx, _changed: &Changed) {}

    /// Dispatches a template event binding to the named handler.
    fn handle(&mut self, _ctx: &mut Ctx, _handler: &str, _event: &UiEvent) {}

    /// Evaluates the named computed property.
    fn compute(&self, _store: &PropertyStore, _name: &str) -> Value {
        Value::Undefined
    }
}
