//! Emits the LitElement-variant TypeScript class for one component:
//! plain class, `static properties`, light DOM, `el-<name>` host class,
//! notify pass in `update()` — the shape of the org's hand-written
//! components (see web_modules' lit-element example and the Schuhkarton
//! catalog), with delegating members into the co-located impl partial.

use uic_core::{ComponentDef, DefaultValue, JsType, Notify, PropertyMeta};
use uic_template::{AttrPart, Attribute, Expr, Node};

use crate::camel_case;

/// The LitNotify port shared by all generated components.
pub const RUNTIME_TS: &str = r#"// GENERATED by ui_components (uic_codegen_web). DO NOT EDIT.
// Port of the catalog's LitNotify mixin: after each update, fires one event
// per changed property with `notify` set. A `notify` string names the event;
// `notify: true` fires `<attribute || property>-changed`. The detail carries
// { property, value, oldValue }.

type NotifyDeclaration = {
  notify?: boolean | string;
  attribute?: boolean | string;
};

export function notifyProperties(
  el: HTMLElement,
  properties: Record<string, NotifyDeclaration>,
  changed: Map<PropertyKey, unknown>,
): void {
  for (const [property, oldValue] of changed) {
    const declaration = properties[String(property)];
    if (!declaration || !declaration.notify) {
      continue;
    }
    const base =
      typeof declaration.attribute === 'string' ? declaration.attribute : String(property);
    const type = typeof declaration.notify === 'string' ? declaration.notify : `${base}-changed`;
    const value = (el as unknown as Record<string, unknown>)[String(property)];
    el.dispatchEvent(new CustomEvent(type, { detail: { property, value, oldValue } }));
  }
}
"#;

pub fn emit_component(def: &'static ComponentDef) -> String {
    let class = def.class_name;
    let tag = def.tag_name;
    let template = def.template();
    let has_conditionals = template_has_if(&template.roots);
    let has_impl = !def.handlers.is_empty() || !def.computed.is_empty();
    let has_notify = def
        .properties
        .iter()
        .any(|p| !matches!(p.notify, Notify::No));

    let mut out = String::new();
    out.push_str(&format!(
        "// GENERATED by ui_components (uic_codegen_web) from {}. DO NOT EDIT.\n",
        def.module_path
    ));
    let lit_imports = if has_conditionals {
        "LitElement, html, nothing"
    } else {
        "LitElement, html"
    };
    out.push_str(&format!("import {{ {lit_imports} }} from 'lit';\n"));
    out.push('\n');
    if has_notify {
        out.push_str("import { notifyProperties } from './uic-runtime.js';\n");
    }
    if has_impl {
        out.push_str(&format!("import * as impl from './{tag}.impl.js';\n"));
    }
    if has_notify || has_impl {
        out.push('\n');
    }

    out.push_str(&format!("export class {class} extends LitElement {{\n"));
    out.push_str(&format!("  static tagName = '{tag}';\n\n"));

    out.push_str("  static properties = {\n");
    for prop in def.properties {
        out.push_str(&format!(
            "    {}: {{ {} }},\n",
            prop.js_name,
            property_options(prop)
        ));
    }
    out.push_str("  };\n\n");

    for prop in def.properties {
        out.push_str(&format!("  {}\n", field_declaration(prop)));
    }
    out.push('\n');

    out.push_str(
        "  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.\n\
         \x20 createRenderRoot(): this {\n\
         \x20   return this;\n\
         \x20 }\n\n",
    );
    out.push_str(&format!(
        "  // ExternalStyles pattern: external stylesheets target .el-{}.\n\
         \x20 connectedCallback(): void {{\n\
         \x20   super.connectedCallback();\n\
         \x20   this.classList.add('el-{}');\n\
         \x20 }}\n\n",
        def.style_id, def.style_id
    ));

    if has_notify {
        out.push_str(&format!(
            "  // LitNotify port: fires the *-changed events after each update.\n\
             \x20 update(changed: Map<PropertyKey, unknown>): void {{\n\
             \x20   super.update(changed);\n\
             \x20   notifyProperties(this, {class}.properties, changed);\n\
             \x20 }}\n\n"
        ));
    }

    for computed in def.computed {
        let member = camel_case(computed);
        out.push_str(&format!(
            "  private get {member}() {{\n\
             \x20   return impl.{member}(this);\n\
             \x20 }}\n\n"
        ));
    }
    for handler in def.handlers {
        let member = camel_case(handler.name);
        out.push_str(&format!(
            "  private {member}(e: Event): void {{\n\
             \x20   impl.{member}(this, e);\n\
             \x20 }}\n\n"
        ));
    }

    out.push_str("  render() {\n    return html`");
    emit_nodes(&template.roots, def, &mut out);
    out.push_str("`;\n  }\n");

    out.push_str("}\n\n");
    out.push_str(&format!(
        "customElements.define({class}.tagName, {class});\n"
    ));
    out
}

fn property_options(prop: &PropertyMeta) -> String {
    let mut options = vec![format!(
        "type: {}",
        match prop.js_type {
            JsType::String => "String",
            JsType::Number => "Number",
            JsType::Boolean => "Boolean",
        }
    )];
    // Lit's default attribute is the lowercased property name; only spell
    // out deviations (the dash-case of multi-word properties).
    if let Some(attribute) = prop.attribute {
        if attribute != prop.js_name.to_lowercase() {
            options.push(format!("attribute: '{attribute}'"));
        }
    }
    if prop.reflect {
        options.push("reflect: true".to_string());
    }
    match prop.notify {
        Notify::No => {}
        Notify::Auto => options.push("notify: true".to_string()),
        Notify::Named(name) => options.push(format!("notify: '{name}'")),
    }
    options.join(", ")
}

fn field_declaration(prop: &PropertyMeta) -> String {
    let ts_type = match prop.js_type {
        JsType::String => "string",
        JsType::Number => "number",
        JsType::Boolean => "boolean",
    };
    match prop.default {
        DefaultValue::Undefined => format!("{}?: {ts_type};", prop.js_name),
        DefaultValue::Str(s) => format!("{} = '{}';", prop.js_name, escape_single_quoted(s)),
        DefaultValue::Num(n) => format!("{} = {n};", prop.js_name),
        DefaultValue::Bool(b) => format!("{} = {b};", prop.js_name),
    }
}

fn template_has_if(nodes: &[Node]) -> bool {
    nodes.iter().any(|node| match node {
        Node::If { .. } => true,
        Node::Element(el) => template_has_if(&el.children),
        _ => false,
    })
}

/// A hole expression as a JS expression on `this`.
fn expr_js(expr: &Expr, def: &ComponentDef) -> String {
    let member = match def.property(expr.ident()) {
        Some(prop) => prop.js_name.to_string(),
        // Not a property: a computed getter generated on the class.
        None => camel_case(expr.ident()),
    };
    match expr {
        Expr::Ident(_) => format!("this.{member}"),
        Expr::Not(_) => format!("!this.{member}"),
    }
}

/// Escapes raw template text for a JS template literal.
fn escape_lit_text(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace("${", "\\${")
}

fn escape_single_quoted(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "\\'")
}

fn emit_nodes(nodes: &[Node], def: &ComponentDef, out: &mut String) {
    for node in nodes {
        match node {
            Node::Text(text) => out.push_str(&escape_lit_text(text)),
            Node::TextHole(expr) => {
                out.push_str("${");
                out.push_str(&expr_js(expr, def));
                out.push('}');
            }
            Node::If { cond, then } => {
                out.push_str("${");
                out.push_str(&expr_js(cond, def));
                out.push_str(" ? html`");
                emit_nodes(then, def, out);
                out.push_str("` : nothing}");
            }
            Node::Element(el) => {
                out.push('<');
                out.push_str(&el.tag);
                for attr in &el.attrs {
                    out.push(' ');
                    emit_attr(attr, def, out);
                }
                out.push('>');
                if !is_void(&el.tag) {
                    emit_nodes(&el.children, def, out);
                    out.push_str("</");
                    out.push_str(&el.tag);
                    out.push('>');
                }
            }
        }
    }
}

fn emit_attr(attr: &Attribute, def: &ComponentDef, out: &mut String) {
    match attr {
        Attribute::Static { name, value } => {
            if value.is_empty() {
                out.push_str(name);
            } else {
                out.push_str(&format!("{name}=\"{}\"", escape_lit_text(value)));
            }
        }
        Attribute::Attr { name, parts } => match parts.as_slice() {
            [AttrPart::Expr(expr)] => {
                out.push_str(&format!("{name}=${{{}}}", expr_js(expr, def)));
            }
            parts => {
                out.push_str(&format!("{name}=\""));
                for part in parts {
                    match part {
                        AttrPart::Static(text) => out.push_str(&escape_lit_text(text)),
                        AttrPart::Expr(expr) => {
                            out.push_str(&format!("${{{}}}", expr_js(expr, def)));
                        }
                    }
                }
                out.push('"');
            }
        },
        Attribute::Bool { name, expr } => {
            out.push_str(&format!("?{name}=${{{}}}", expr_js(expr, def)));
        }
        Attribute::Prop { name, expr } => {
            out.push_str(&format!(".{name}=${{{}}}", expr_js(expr, def)));
        }
        Attribute::Event { name, handler } => {
            out.push_str(&format!("@{name}=${{this.{}}}", camel_case(handler)));
        }
    }
}

fn is_void(tag: &str) -> bool {
    matches!(
        tag,
        "area"
            | "base"
            | "br"
            | "col"
            | "embed"
            | "hr"
            | "img"
            | "input"
            | "link"
            | "meta"
            | "param"
            | "source"
            | "track"
            | "wbr"
    )
}
