//! Emits the LitElement-variant TypeScript class for one component:
//! plain class, `static properties`, light DOM, `el-<name>` host class,
//! notify pass in `update()` — the shape of the org's hand-written
//! components (see web_modules' lit-element example and the Schuhkarton
//! catalog), with delegating members into the co-located impl partial.

use uic_core::{ComponentDef, CustomElementRegistry, DefaultValue, JsType, Notify, PropertyMeta};
use uic_template::{AttrPart, Attribute, Element, Expr, Node};

use crate::camel_case;

/// The LitNotify port shared by all generated components.
pub const RUNTIME_TS: &str = r#"// GENERATED by ui_components (uic_codegen_web). DO NOT EDIT.
// Port of the catalog's LitNotify mixin: after each update, fires one event
// per changed property with `notify` set. A `notify` string names the event;
// `notify: true` fires `<attribute || property>-changed`. The detail carries
// { property, value, oldValue }.

type NotifyDeclaration = {
  notify?: boolean | string;
  attribute?: boolean | string;
};

export function notifyProperties(
  el: HTMLElement,
  properties: Record<string, NotifyDeclaration>,
  changed: Map<PropertyKey, unknown>,
): void {
  for (const [property, oldValue] of changed) {
    const declaration = properties[String(property)];
    if (!declaration || !declaration.notify) {
      continue;
    }
    const base =
      typeof declaration.attribute === 'string' ? declaration.attribute : String(property);
    const type = typeof declaration.notify === 'string' ? declaration.notify : `${base}-changed`;
    const value = (el as unknown as Record<string, unknown>)[String(property)];
    el.dispatchEvent(new CustomEvent(type, { detail: { property, value, oldValue } }));
  }
}

// One entry of a select option list (ADR 0006): `value` commits, `short` is
// the closed-layer text, `label` the open-list text; both fall back to value.
export type SelectOption = { value: string; short?: string; label?: string };
"#;

pub fn emit_component(def: &'static ComponentDef) -> String {
    let class = def.class_name;
    let tag = def.tag_name;
    let template = def.template();
    let has_conditionals = template_has_if(&template.roots);
    let has_impl = !def.handlers.is_empty() || !def.computed.is_empty();
    let has_notify = def
        .properties
        .iter()
        .any(|p| !matches!(p.notify, Notify::No));
    let has_zoned = def.properties.iter().any(|p| p.js_type == JsType::Zoned);
    let has_options = def.properties.iter().any(|p| p.js_type == JsType::Options);
    // Optional lifecycle hooks: wired when the impl partial exports them.
    let has_will_update = def
        .web_impl
        .is_some_and(|source| crate::exported_names(source).contains("willUpdate"));
    let has_updated = def
        .web_impl
        .is_some_and(|source| crate::exported_names(source).contains("updated"));
    let has_connected = def
        .web_impl
        .is_some_and(|source| crate::exported_names(source).contains("connected"));

    let mut out = String::new();
    out.push_str(&format!(
        "// GENERATED by ui_components (uic_codegen_web) from {}. DO NOT EDIT.\n",
        def.module_path
    ));
    let lit_imports = if has_conditionals {
        "LitElement, html, nothing"
    } else {
        "LitElement, html"
    };
    out.push_str(&format!("import {{ {lit_imports} }} from 'lit';\n"));
    if has_zoned {
        // Type-only: erased from the runtime JS; the impl partial carries
        // the real temporal-polyfill import.
        out.push_str("import type { Temporal } from 'temporal-polyfill';\n");
    }
    if has_options {
        out.push_str("import type { SelectOption } from './uic-runtime.js';\n");
    }
    out.push('\n');
    if has_notify {
        out.push_str("import { notifyProperties } from './uic-runtime.js';\n");
    }
    if has_impl || has_will_update || has_updated || has_connected {
        out.push_str(&format!("import * as impl from './{tag}.impl.js';\n"));
    }
    // Registered nested elements define themselves on import, so a consumer
    // loading this module gets its children too (unregistered custom tags
    // are the consumer's own).
    let child_tags: Vec<&str> = template
        .custom_tags()
        .into_iter()
        .filter(|child| *child != tag && CustomElementRegistry::get(child).is_some())
        .collect();
    for child in &child_tags {
        out.push_str(&format!("import './{child}.js';\n"));
    }
    if has_notify
        || has_impl
        || has_will_update
        || has_updated
        || has_connected
        || !child_tags.is_empty()
    {
        out.push('\n');
    }

    out.push_str(&format!("export class {class} extends LitElement {{\n"));
    out.push_str(&format!("  static tagName = '{tag}';\n\n"));

    out.push_str("  static properties = {\n");
    for prop in def.properties {
        out.push_str(&format!(
            "    {}: {{ {} }},\n",
            prop.js_name,
            property_options(prop)
        ));
    }
    out.push_str("  };\n\n");

    for prop in def.properties {
        out.push_str(&format!("  {}\n", field_declaration(prop)));
    }
    out.push('\n');

    out.push_str(
        "  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.\n\
         \x20 createRenderRoot(): this {\n\
         \x20   return this;\n\
         \x20 }\n\n",
    );
    let host_classes = match def.shared_style_id {
        Some(shared) => format!("'el-{shared}', 'el-{}'", def.style_id),
        None => format!("'el-{}'", def.style_id),
    };
    let connected_call = if has_connected {
        // Optional lifecycle hook, present in the impl partial.
        "\n\x20   impl.connected(this);"
    } else {
        ""
    };
    out.push_str(&format!(
        "  // ExternalStyles pattern: external stylesheets target .el-{}.\n\
         \x20 connectedCallback(): void {{\n\
         \x20   super.connectedCallback();\n\
         \x20   this.classList.add({host_classes});{connected_call}\n\
         \x20 }}\n\n",
        def.style_id
    ));

    if has_will_update {
        out.push_str(
            "  // Optional lifecycle hook, present in the impl partial.\n\
             \x20 willUpdate(changed: Map<PropertyKey, unknown>): void {\n\
             \x20   super.willUpdate(changed);\n\
             \x20   impl.willUpdate(this, changed);\n\
             \x20 }\n\n",
        );
    }

    if has_updated {
        out.push_str(
            "  // Optional lifecycle hook, present in the impl partial.\n\
             \x20 updated(changed: Map<PropertyKey, unknown>): void {\n\
             \x20   super.updated(changed);\n\
             \x20   impl.updated(this, changed);\n\
             \x20 }\n\n",
        );
    }

    if has_notify {
        out.push_str(&format!(
            "  // LitNotify port: fires the *-changed events after each update.\n\
             \x20 update(changed: Map<PropertyKey, unknown>): void {{\n\
             \x20   super.update(changed);\n\
             \x20   notifyProperties(this, {class}.properties, changed);\n\
             \x20 }}\n\n"
        ));
    }

    for computed in def.computed {
        let member = camel_case(computed);
        out.push_str(&format!(
            "  private get {member}() {{\n\
             \x20   return impl.{member}(this);\n\
             \x20 }}\n\n"
        ));
    }
    for handler in def.handlers {
        let member = camel_case(handler.name);
        out.push_str(&format!(
            "  private {member}(e: Event): void {{\n\
             \x20   impl.{member}(this, e);\n\
             \x20 }}\n\n"
        ));
    }

    out.push_str("  render() {\n    return html`");
    emit_nodes(&template.roots, def, &mut out);
    out.push_str("`;\n  }\n");

    out.push_str("}\n\n");
    out.push_str(&format!(
        "customElements.define({class}.tagName, {class});\n"
    ));
    out
}

fn property_options(prop: &PropertyMeta) -> String {
    // Object-valued properties: no converter runs (attribute: false) and the
    // default `!==` hasChanged applies — reference semantics like the catalog.
    let mut options = match prop.js_type {
        JsType::Zoned | JsType::Options => vec!["attribute: false".to_string()],
        JsType::String => vec!["type: String".to_string()],
        JsType::Number => vec!["type: Number".to_string()],
        JsType::Boolean => vec!["type: Boolean".to_string()],
    };
    // Lit's default attribute is the lowercased property name; only spell
    // out deviations (the dash-case of multi-word properties).
    if let Some(attribute) = prop.attribute {
        if attribute != prop.js_name.to_lowercase() {
            options.push(format!("attribute: '{attribute}'"));
        }
    }
    if prop.reflect {
        options.push("reflect: true".to_string());
    }
    match prop.notify {
        Notify::No => {}
        Notify::Auto => options.push("notify: true".to_string()),
        Notify::Named(name) => options.push(format!("notify: '{name}'")),
    }
    options.join(", ")
}

fn field_declaration(prop: &PropertyMeta) -> String {
    let ts_type = match prop.js_type {
        JsType::String => "string",
        JsType::Number => "number",
        JsType::Boolean => "boolean",
        JsType::Zoned => "Temporal.ZonedDateTime | null",
        JsType::Options => "SelectOption[]",
    };
    let initializer = match prop.default {
        DefaultValue::Undefined => return format!("{}?: {ts_type};", prop.js_name),
        DefaultValue::Str(s) => format!("'{}'", escape_single_quoted(s)),
        DefaultValue::Num(n) => n.to_string(),
        DefaultValue::Bool(b) => b.to_string(),
        // A bare `[]` would infer `never[]`; spell the element type.
        DefaultValue::EmptyOptions => return format!("{}: {ts_type} = [];", prop.js_name),
    };
    if prop.optional {
        // Optional with a default: nullable field, initialized.
        format!("{}: {ts_type} | null = {initializer};", prop.js_name)
    } else {
        format!("{} = {initializer};", prop.js_name)
    }
}

fn template_has_if(nodes: &[Node]) -> bool {
    nodes.iter().any(|node| match node {
        Node::If { .. } => true,
        Node::Element(el) => template_has_if(&el.children),
        _ => false,
    })
}

/// A hole expression as a JS expression on `this`.
fn expr_js(expr: &Expr, def: &ComponentDef) -> String {
    let member = match def.property(expr.ident()) {
        Some(prop) => prop.js_name.to_string(),
        // Not a property: a computed getter generated on the class.
        None => camel_case(expr.ident()),
    };
    match expr {
        Expr::Ident(_) => format!("this.{member}"),
        Expr::Not(_) => format!("!this.{member}"),
    }
}

/// Escapes raw template text for a JS template literal.
fn escape_lit_text(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace("${", "\\${")
}

fn escape_single_quoted(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "\\'")
}

fn emit_nodes(nodes: &[Node], def: &ComponentDef, out: &mut String) {
    for node in nodes {
        match node {
            Node::Text(text) => out.push_str(&escape_lit_text(text)),
            Node::TextHole(expr) => {
                out.push_str("${");
                out.push_str(&expr_js(expr, def));
                out.push('}');
            }
            Node::If { cond, then } => {
                out.push_str("${");
                out.push_str(&expr_js(cond, def));
                out.push_str(" ? html`");
                emit_nodes(then, def, out);
                out.push_str("` : nothing}");
            }
            Node::Element(el) => {
                let select_options = if el.tag == "select" {
                    el.attrs.iter().find_map(|attr| match attr {
                        Attribute::Prop { name, expr } if name == "options" => Some(expr),
                        _ => None,
                    })
                } else {
                    None
                };
                out.push('<');
                out.push_str(&el.tag);
                for attr in &el.attrs {
                    // Native selects have no options property; the binding
                    // becomes the <option> children below (ADR 0006).
                    if select_options.is_some()
                        && matches!(attr, Attribute::Prop { name, .. } if name == "options")
                    {
                        continue;
                    }
                    out.push(' ');
                    emit_attr(attr, def, out);
                }
                out.push('>');
                if let Some(options_expr) = select_options {
                    emit_select_options(el, options_expr, def, out);
                    out.push_str("</select>");
                } else if !is_void(&el.tag) {
                    emit_nodes(&el.children, def, out);
                    out.push_str("</");
                    out.push_str(&el.tag);
                    out.push('>');
                }
            }
        }
    }
}

/// Expands a `<select .options=${…}>` binding into its `<option>` children
/// (ADR 0006). The closed front layer (class `input-front`) prefers the
/// compact `short` label; `?selected` compares against the select's own
/// `.value` binding (its computed already renders null as `""`), keeping
/// the first render correct before Lit assigns the value property.
fn emit_select_options(el: &Element, options_expr: &Expr, def: &ComponentDef, out: &mut String) {
    let label = if has_class_token(el, "input-front") {
        "option.short || option.label || option.value"
    } else {
        "option.label || option.value"
    };
    let selected = el
        .attrs
        .iter()
        .find_map(|attr| match attr {
            Attribute::Prop { name, expr } if name == "value" => Some(expr),
            _ => None,
        })
        .map(|expr| format!(" ?selected=${{{} === option.value}}", expr_js(expr, def)))
        .unwrap_or_default();
    out.push_str(&format!(
        "${{{}.map((option) => html`<option value=${{option.value}}{selected}>\
         ${{{label}}}</option>`)}}",
        expr_js(options_expr, def)
    ));
}

/// Whether the element's class attribute contains the token in a static part.
fn has_class_token(el: &Element, token: &str) -> bool {
    el.attrs.iter().any(|attr| {
        match attr {
        Attribute::Static { name, value } if name == "class" => {
            value.split_whitespace().any(|t| t == token)
        }
        Attribute::Attr { name, parts } if name == "class" => parts.iter().any(|part| {
            matches!(part, AttrPart::Static(text) if text.split_whitespace().any(|t| t == token))
        }),
        _ => false,
    }
    })
}

fn emit_attr(attr: &Attribute, def: &ComponentDef, out: &mut String) {
    match attr {
        Attribute::Static { name, value } => {
            if value.is_empty() {
                out.push_str(name);
            } else {
                out.push_str(&format!("{name}=\"{}\"", escape_lit_text(value)));
            }
        }
        Attribute::Attr { name, parts } => match parts.as_slice() {
            [AttrPart::Expr(expr)] => {
                out.push_str(&format!("{name}=${{{}}}", expr_js(expr, def)));
            }
            parts => {
                out.push_str(&format!("{name}=\""));
                for part in parts {
                    match part {
                        AttrPart::Static(text) => out.push_str(&escape_lit_text(text)),
                        AttrPart::Expr(expr) => {
                            out.push_str(&format!("${{{}}}", expr_js(expr, def)));
                        }
                    }
                }
                out.push('"');
            }
        },
        Attribute::Bool { name, expr } => {
            out.push_str(&format!("?{name}=${{{}}}", expr_js(expr, def)));
        }
        Attribute::Prop { name, expr } => {
            out.push_str(&format!(".{name}=${{{}}}", expr_js(expr, def)));
        }
        Attribute::Event { name, handler } => {
            out.push_str(&format!("@{name}=${{this.{}}}", camel_case(handler)));
        }
    }
}

fn is_void(tag: &str) -> bool {
    matches!(
        tag,
        "area"
            | "base"
            | "br"
            | "col"
            | "embed"
            | "hr"
            | "img"
            | "input"
            | "link"
            | "meta"
            | "param"
            | "source"
            | "track"
            | "wbr"
    )
}
