// GENERATED by ui_components (uic_codegen_web). DO NOT EDIT.
// Hand-written helpers shared by the co-located .impl.ts partials, the
// idioms every twin re-spelled: notify-detail extraction and the text
// family's trim-commit.

// The notify detail's value, null when absent; a child's *-changed payload.
export function detailValue(e: Event): unknown {
  return (e as CustomEvent).detail?.value ?? null;
}

// The detail's value as text, '' when absent or null.
export function detailString(e: Event): string {
  const value = (e as CustomEvent).detail?.value;
  return typeof value === 'string' ? value : '';
}

// The text family's commit rule: trimmed text, and an empty commit becomes
// null with allow-null (the empty string without).
export function trimmedValue(raw: string, allowNull: boolean): string | null {
  const trimmed = raw.trim();
  if (trimmed === '') {
    return allowNull ? null : '';
  }
  return trimmed;
}
