// GENERATED by ui_components (uic_codegen_web) from ui_components_demo::app_root. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';
import type { SelectOption } from './uic-runtime.js';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './app-root.impl.js';
import './input-date.js';
import './input-date-range.js';
import './input-number.js';
import './input-secret.js';
import './input-select.js';
import './input-suggestion.js';
import './input-text.js';
import './input-textarea.js';
import './input-timezone.js';
import './nav-tabs.js';

export class AppRoot extends LitElement {
  static tagName = 'app-root';

  static properties = {
    state: { attribute: false, notify: true },
    wordSuggestions: { attribute: false },
  };

  state: Record<string, unknown> = {};
  wordSuggestions: SelectOption[] = [];

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-app-root.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-app-root');
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, AppRoot.properties, changed);
  }

  private get amount() {
    return impl.amount(this);
  }

  private get date() {
    return impl.date(this);
  }

  private get end() {
    return impl.end(this);
  }

  private get essay() {
    return impl.essay(this);
  }

  private get note() {
    return impl.note(this);
  }

  private get pick() {
    return impl.pick(this);
  }

  private get pickOptions() {
    return impl.pickOptions(this);
  }

  private get showAbout() {
    return impl.showAbout(this);
  }

  private get showForm() {
    return impl.showForm(this);
  }

  private get start() {
    return impl.start(this);
  }

  private get stateLine() {
    return impl.stateLine(this);
  }

  private get tab() {
    return impl.tab(this);
  }

  private get tabOptions() {
    return impl.tabOptions(this);
  }

  private get token() {
    return impl.token(this);
  }

  private get word() {
    return impl.word(this);
  }

  private get zone() {
    return impl.zone(this);
  }

  private onAmount(e: Event): void {
    impl.onAmount(this, e);
  }

  private onDate(e: Event): void {
    impl.onDate(this, e);
  }

  private onEnd(e: Event): void {
    impl.onEnd(this, e);
  }

  private onEssay(e: Event): void {
    impl.onEssay(this, e);
  }

  private onNote(e: Event): void {
    impl.onNote(this, e);
  }

  private onPick(e: Event): void {
    impl.onPick(this, e);
  }

  private onStart(e: Event): void {
    impl.onStart(this, e);
  }

  private onTab(e: Event): void {
    impl.onTab(this, e);
  }

  private onToken(e: Event): void {
    impl.onToken(this, e);
  }

  private onWord(e: Event): void {
    impl.onWord(this, e);
  }

  private onWordQuery(e: Event): void {
    impl.onWordQuery(this, e);
  }

  private onZone(e: Event): void {
    impl.onZone(this, e);
  }

  render() {
    return html`
<div data-qa="app-shell">
  <div class="card" data-qa="app-card">
    <div class="card-header">
      <nav-tabs class="card-header-tabs" .options=${this.tabOptions} .value=${this.tab} @value-changed=${this.onTab}></nav-tabs>
    </div>
    <div class="card-body">
      ${this.showForm ? html`
        
        <div data-qa="app-form">
          
          <input-date label="Date of purchase" hint="Partials complete: 2024 becomes 2024-01-01 00:00:00" min="2020-01-01" max="2030-12-31" default-timezone="Europe/Berlin" show-timezone class="mb-4 d-block w-100" .value=${this.date} @value-changed=${this.onDate}></input-date>
          <input-date-range label="Stay" hint="The end never precedes the start; both ends commit the interval" hide-time class="mb-4 d-block" .start=${this.start} .end=${this.end} @start-changed=${this.onStart} @end-changed=${this.onEnd}></input-date-range>
          <input-text label="Note" hint="Trimmed on commit; empty becomes null" placeholder="free text" allow-null class="mb-4 d-block" .value=${this.note} @value-changed=${this.onNote}></input-text>
          <input-number label="Amount" hint="Comma or dot decimals; dots group thousands" unit="€" allow-null class="mb-4 d-block" .value=${this.amount} @value-changed=${this.onAmount}></input-number>
          <input-select label="Time zone" hint="Empty commits null once a default is set" default="Pick a zone" data-qa="select-demo" class="mb-4 d-block" .value=${this.pick} .options=${this.pickOptions} @value-changed=${this.onPick}></input-select>
          <input-textarea label="Comment" hint="Grows with its content up to max-lines" max-lines="6" placeholder="multi-line text" class="mb-4 d-block" .value=${this.essay} @value-changed=${this.onEssay}></input-textarea>
          <input-timezone label="Default time zone" hint="The browser zone list; empty commits null" default class="mb-4 d-block" .value=${this.zone} @value-changed=${this.onZone}></input-timezone>
          <input-suggestion label="Word" hint="Typeahead over the demo word pool" placeholder="start typing" allow-null class="mb-4 d-block" .value=${this.word} .suggestions=${this.wordSuggestions} @value-changed=${this.onWord} @query-changed=${this.onWordQuery}></input-suggestion>
          
          <input-secret label="API token" hint="Reveal to read it; edit to set a new one" editable class="mb-0 d-block w-100" .value=${this.token} @value-changed=${this.onToken}></input-secret>
        </div>
      ` : nothing}
      ${this.showAbout ? html`
        
        <div data-qa="app-about">
          <p class="mb-3">Every component on the Form tab is defined once in Rust and rendered twice: as a LitElement custom element in the browser and as a widget tree in the terminal pane beside it.</p>
          <p class="mb-3">The form binds each control to one shared state object; commits notify upward, values flow back down, and any transport that carries the state snapshot keeps both targets in step.</p>
          <p class="mb-0">The templates speak a closed grammar, option lists travel as data, and connectors answer the word typeahead through one query interface per target.</p>
        </div>
      ` : nothing}
    </div>
  </div>
  
  <p class="small text-body-secondary mt-4 mb-0" data-qa="state-line">state · ${this.stateLine}</p>
</div>
`;
  }
}

customElements.define(AppRoot.tagName, AppRoot);
