// GENERATED by ui_components (uic_codegen_web) from ui_components::input::date. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';
import type { Temporal } from 'temporal-polyfill';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-date.impl.js';
import './input-timezone.js';

export class InputDate extends LitElement {
  static tagName = 'input-date';

  static properties = {
    value: { type: String, notify: true },
    date: { attribute: false, notify: true },
    timezone: { type: String, notify: true },
    defaultTimezone: { type: String, attribute: 'default-timezone' },
    min: { type: String },
    max: { type: String },
    placeholder: { type: String },
    showTimezone: { type: Boolean, attribute: 'show-timezone', reflect: true },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value = '';
  date?: Temporal.ZonedDateTime | null;
  timezone?: string;
  defaultTimezone?: string;
  min?: string;
  max?: string;
  placeholder?: string;
  showTimezone = false;
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-date.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-date');
  }

  // Optional lifecycle hook, present in the impl partial.
  willUpdate(changed: Map<PropertyKey, unknown>): void {
    super.willUpdate(changed);
    impl.willUpdate(this, changed);
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputDate.properties, changed);
  }

  private get placeholderText() {
    return impl.placeholderText(this);
  }

  private get timezoneDefault() {
    return impl.timezoneDefault(this);
  }

  private onChange(e: Event): void {
    impl.onChange(this, e);
  }

  private onTimezoneChanged(e: Event): void {
    impl.onTimezoneChanged(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    <input type="text" class="form-control text-center flex-grow-1" data-tui="date-input" data-qa="date-input" .value=${this.value} placeholder=${this.placeholderText} ?disabled=${this.disabled} @change=${this.onChange}>
${this.showTimezone ? html`
  
  <input-timezone data-qa="timezone-input" class="flex-shrink-0 w-auto" embedded seamless ?disabled=${!this.showTimezone} .value=${this.timezone} .default=${this.timezoneDefault} @value-changed=${this.onTimezoneChanged}></input-timezone>
` : nothing}

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputDate.tagName, InputDate);
