// GENERATED by ui_components (uic_codegen_web) from ui_components::input::date_range. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-date-range.impl.js';
import './input-date.js';
import './input-timezone.js';

export class InputDateRange extends LitElement {
  static tagName = 'input-date-range';

  static properties = {
    value: { type: String, notify: true },
    start: { type: String, notify: true },
    end: { type: String, notify: true },
    complete: { type: Boolean, reflect: true },
    timezone: { type: String, notify: true },
    defaultTimezone: { type: String, attribute: 'default-timezone' },
    showTimezone: { type: Boolean, attribute: 'show-timezone', reflect: true },
    hideTime: { type: Boolean, attribute: 'hide-time', reflect: true },
    hideSeconds: { type: Boolean, attribute: 'hide-seconds', reflect: true },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value = '';
  start = '';
  end = '';
  complete = false;
  timezone?: string;
  defaultTimezone?: string;
  showTimezone = false;
  hideTime = false;
  hideSeconds = false;
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-date-range.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-date-range');
  }

  // Optional lifecycle hook, present in the impl partial.
  willUpdate(changed: Map<PropertyKey, unknown>): void {
    super.willUpdate(changed);
    impl.willUpdate(this, changed);
  }

  // Optional lifecycle hook, present in the impl partial.
  updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    impl.updated(this, changed);
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputDateRange.properties, changed);
  }

  private get rangeTimezone() {
    return impl.rangeTimezone(this);
  }

  private get timezoneDefault() {
    return impl.timezoneDefault(this);
  }

  private onEndChanged(e: Event): void {
    impl.onEndChanged(this, e);
  }

  private onStartChanged(e: Event): void {
    impl.onStartChanged(this, e);
  }

  private onTimezoneChanged(e: Event): void {
    impl.onTimezoneChanged(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    
<div class="d-flex flex-wrap w-100 gap-0" data-qa="range-row">
  <div class="d-flex flex-nowrap flex-grow-1 flex-shrink-0 gap-0">
    <input-date data-qa="start-input" class="flex-grow-1" seamless default-timezone=${this.rangeTimezone} ?hide-time=${this.hideTime} ?hide-seconds=${this.hideSeconds} .value=${this.start} ?disabled=${this.disabled} @value-changed=${this.onStartChanged}></input-date>
  </div>
  <div class="d-flex flex-nowrap flex-grow-1 flex-shrink-0 gap-0">
    <span class="input-group-text text-body-secondary" data-qa="range-separator">-</span>
    <input-date data-qa="end-input" class="flex-grow-1" seamless end-of default-timezone=${this.rangeTimezone} ?hide-time=${this.hideTime} ?hide-seconds=${this.hideSeconds} .value=${this.end} ?disabled=${this.disabled} @value-changed=${this.onEndChanged}></input-date>
  </div>
  ${this.showTimezone ? html`
    
    <input-timezone data-qa="range-timezone" class="flex-shrink-0 w-auto" embedded seamless ?disabled=${!this.showTimezone} .value=${this.timezone} .default=${this.timezoneDefault} @value-changed=${this.onTimezoneChanged}></input-timezone>
  ` : nothing}
</div>

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputDateRange.tagName, InputDateRange);
