// GENERATED by ui_components (uic_codegen_web) from ui_components::input::select. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';
import type { SelectOption } from './uic-runtime.js';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-select.impl.js';

export class InputSelect extends LitElement {
  static tagName = 'input-select';

  static properties = {
    value: { type: String, notify: true },
    default: { type: String },
    embedded: { type: Boolean, reflect: true },
    options: { attribute: false },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value: string | null = '';
  default?: string;
  embedded = false;
  options: SelectOption[] = [];
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-select.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-select');
  }

  // Optional lifecycle hook, present in the impl partial.
  willUpdate(changed: Map<PropertyKey, unknown>): void {
    super.willUpdate(changed);
    impl.willUpdate(this, changed);
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputSelect.properties, changed);
  }

  private get embeddedClass() {
    return impl.embeddedClass(this);
  }

  private get formValue() {
    return impl.formValue(this);
  }

  private get frontClass() {
    return impl.frontClass(this);
  }

  private get selectOptions() {
    return impl.selectOptions(this);
  }

  private onChange(e: Event): void {
    impl.onChange(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    <div class="position-relative form-select border-input flex-grow-1 flex-shrink-1 ${this.embeddedClass}">
  <select class="input-front ${this.frontClass}" tabindex="-1" ?disabled=${this.disabled} .value=${this.formValue}>${this.selectOptions.map((option) => html`<option value=${option.value} ?selected=${this.formValue === option.value}>${option.short || option.label || option.value}</option>`)}</select>
  <select class="input-back" data-tui="select" data-qa="select-input" ?disabled=${this.disabled} .value=${this.formValue} @change=${this.onChange}>${this.selectOptions.map((option) => html`<option value=${option.value} ?selected=${this.formValue === option.value}>${option.label || option.value}</option>`)}</select>
</div>

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputSelect.tagName, InputSelect);
