// GENERATED by ui_components (uic_codegen_web) from ui_components::input::secret. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-secret.impl.js';
import './uic-icon.js';

export class InputSecret extends LitElement {
  static tagName = 'input-secret';

  static properties = {
    value: { type: String, notify: true },
    editable: { type: Boolean, reflect: true },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value: string | null = '';
  editable = false;
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-secret.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-secret');
    impl.connected(this);
  }

  // Optional lifecycle hook, present in the impl partial.
  updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    impl.updated(this, changed);
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputSecret.properties, changed);
  }

  private onChange(e: Event): void {
    impl.onChange(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    <input type="password" class="form-control text-start w-100 font-monospace" data-tui="secret-input" data-qa="secret-input" .value=${this.value} ?readonly=${!this.editable} ?disabled=${this.disabled} @change=${this.onChange}>

<button type="button" class="btn btn-outline-secondary" data-qa="secret-reveal" aria-label="Reveal" aria-pressed="false" hidden>
  <uic-icon data-qa="secret-reveal-icon" name="visibility"></uic-icon>
</button>
<button type="button" class="btn btn-outline-secondary" data-qa="secret-copy" aria-label="Copy to clipboard" hidden>
  <uic-icon data-qa="secret-copy-icon" name="content_copy"></uic-icon>
</button>

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputSecret.tagName, InputSecret);
