// GENERATED by ui_components (uic_codegen_web) from ui_components::input::text. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-text.impl.js';

export class InputText extends LitElement {
  static tagName = 'input-text';

  static properties = {
    value: { type: String, notify: true },
    type: { type: String, reflect: true },
    allowNull: { type: Boolean, attribute: 'allow-null', reflect: true },
    placeholder: { type: String },
    autocomplete: { type: String, reflect: true },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value: string | null = '';
  type = 'text';
  allowNull = false;
  placeholder = '';
  autocomplete = 'one-time-code';
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-text.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-text');
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputText.properties, changed);
  }

  private onChange(e: Event): void {
    impl.onChange(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    <input type=${this.type} class="form-control text-start w-100" data-tui="text-input" data-qa="text-input" .value=${this.value} placeholder=${this.placeholder} autocomplete=${this.autocomplete} ?disabled=${this.disabled} @change=${this.onChange}>

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputText.tagName, InputText);
