// GENERATED by ui_components (uic_codegen_web) from ui_components::input::number. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-number.impl.js';

export class InputNumber extends LitElement {
  static tagName = 'input-number';

  static properties = {
    value: { type: Number, notify: true },
    digits: { type: Number },
    decimals: { type: Number, reflect: true },
    decimalsOptional: { type: Boolean, attribute: 'decimals-optional', reflect: true },
    unit: { type: String },
    placeholder: { type: String },
    placeholderPosition: { type: String, attribute: 'placeholder-position' },
    allowNull: { type: Boolean, attribute: 'allow-null', reflect: true },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value: number | null = 0;
  digits = 4;
  decimals = 2;
  decimalsOptional = false;
  unit?: string;
  placeholder = '';
  placeholderPosition?: string;
  allowNull = false;
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-number.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-number');
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputNumber.properties, changed);
  }

  private get displayValue() {
    return impl.displayValue(this);
  }

  private get inputMode() {
    return impl.inputMode(this);
  }

  private onChange(e: Event): void {
    impl.onChange(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    <input type="text" lang="en-150" inputmode=${this.inputMode} class="form-control text-end flex-grow-1" data-tui="number-input" data-qa="number-input" .value=${this.displayValue} placeholder=${this.placeholder} ?disabled=${this.disabled} @change=${this.onChange}>
${this.unit ? html`
  <span class="input-group-text text-secondary" data-qa="unit">${this.unit}</span>
` : nothing}

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputNumber.tagName, InputNumber);
