// GENERATED by ui_components (uic_codegen_web) from ui_components::input::suggestion. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';
import type { SelectOption } from './uic-runtime.js';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './input-suggestion.impl.js';

export class InputSuggestion extends LitElement {
  static tagName = 'input-suggestion';

  static properties = {
    value: { type: String, notify: true },
    query: { type: String, notify: true },
    suggestions: { attribute: false },
    allowNull: { type: Boolean, attribute: 'allow-null', reflect: true },
    placeholder: { type: String },
    label: { type: String },
    hint: { type: String },
    errorMessage: { type: String, attribute: 'error-message' },
    disabled: { type: Boolean, reflect: true },
    name: { type: String },
    required: { type: Boolean, reflect: true },
    error: { type: Boolean, reflect: true },
    suggested: { type: Boolean, reflect: true },
    seamless: { type: Boolean, reflect: true },
  };

  value: string | null = '';
  query = '';
  suggestions: SelectOption[] = [];
  allowNull = false;
  placeholder = '';
  label?: string;
  hint?: string;
  errorMessage?: string;
  disabled = false;
  name?: string;
  required = false;
  error = false;
  suggested = false;
  seamless = false;

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-input-suggestion.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-input-default', 'el-input-suggestion');
    impl.connected(this);
  }

  // Optional lifecycle hook, present in the impl partial.
  updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    impl.updated(this, changed);
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, InputSuggestion.properties, changed);
  }

  private onChange(e: Event): void {
    impl.onChange(this, e);
  }

  private onInput(e: Event): void {
    impl.onInput(this, e);
  }

  render() {
    return html`${this.label ? html`
  <label class="form-label flex-grow-0 flex-shrink-0">${this.label}</label>
` : nothing}
<div class="input-target p-0 position-relative d-flex flex-grow-1 flex-shrink-0">
  <div class="input-group w-100 flex-nowrap">
    <input type="text" class="form-control text-start w-100" data-tui="suggestion-input" data-qa="suggestion-input" role="combobox" aria-autocomplete="list" .value=${this.value} .options=${this.suggestions} placeholder=${this.placeholder} autocomplete="one-time-code" ?disabled=${this.disabled} @input=${this.onInput} @change=${this.onChange}>
<ul class="dropdown-menu" data-qa="suggestion-list"></ul>

  </div>
</div>
${this.errorMessage ? html`
  <div class="text-start fst-italic text-small mt-1">
    <div class="text-danger">${this.errorMessage}</div>
  </div>
` : nothing}
${!this.errorMessage ? html`
  ${this.hint ? html`
    <div class="text-start fst-italic text-small mt-1">
      <div class="text-muted small">${this.hint}</div>
    </div>
  ` : nothing}
` : nothing}
`;
  }
}

customElements.define(InputSuggestion.tagName, InputSuggestion);
