// GENERATED by ui_components (uic_codegen_web) from ui_components::nav_tabs. DO NOT EDIT.
import { LitElement, html } from 'lit';
import type { SelectOption } from './uic-runtime.js';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './nav-tabs.impl.js';

export class NavTabs extends LitElement {
  static tagName = 'nav-tabs';

  static properties = {
    value: { type: String, notify: true },
    options: { attribute: false },
  };

  value = '';
  options: SelectOption[] = [];

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-nav-tabs.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-nav-tabs');
  }

  // Optional lifecycle hook, present in the impl partial.
  updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    impl.updated(this, changed);
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, NavTabs.properties, changed);
  }

  private onInput(e: Event): void {
    impl.onInput(this, e);
  }

  render() {
    return html`
<ul class="nav nav-tabs" role="tablist" data-tui="tab-bar" data-qa="tab-bar" .value=${this.value} .options=${this.options} @input=${this.onInput}></ul>
`;
  }
}

customElements.define(NavTabs.tagName, NavTabs);
