// GENERATED by ui_components (uic_codegen_web) from ui_components::nav_breadcrumb. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';

import * as impl from './nav-breadcrumb.impl.js';

export class NavBreadcrumb extends LitElement {
  static tagName = 'nav-breadcrumb';

  static properties = {
    items: { attribute: false },
    divider: { type: String },
  };

  items = [];
  divider = '›';

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-nav-breadcrumb.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-nav-breadcrumb');
  }

  private get crumbs() {
    return impl.crumbs(this);
  }

  render() {
    return html`
<nav class="uic-breadcrumb d-flex flex-row flex-wrap gap-2" aria-label="Breadcrumb">
  ${this.crumbs.map((c) => html`
    ${c.sep ? html`
      <span class="uic-breadcrumb-sep text-body-secondary">${c.sep}</span>
    ` : nothing}
    ${c.href ? html`
      <a href=${c.href}>${c.label}</a>
    ` : nothing}
    ${c.plain ? html`
      <span>${c.label}</span>
    ` : nothing}
  `)}
</nav>
`;
  }
}

customElements.define(NavBreadcrumb.tagName, NavBreadcrumb);
