// GENERATED by ui_components (uic_codegen_web) from ui_components::tree. DO NOT EDIT.
import { LitElement, html, nothing } from 'lit';

import { notifyProperties } from './uic-runtime.js';
import * as impl from './uic-tree.impl.js';

export class Tree extends LitElement {
  static tagName = 'uic-tree';

  static properties = {
    nodes: { attribute: false },
    expanded: { attribute: false },
    selected: { type: String, notify: true },
  };

  nodes = [];
  expanded = [];
  selected = '';

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-uic-tree.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-uic-tree');
  }

  // LitNotify port: fires the *-changed events after each update.
  update(changed: Map<PropertyKey, unknown>): void {
    super.update(changed);
    notifyProperties(this, Tree.properties, changed);
  }

  private get rows() {
    return impl.rows(this);
  }

  private onRowClick(e: Event): void {
    impl.onRowClick(this, e);
  }

  render() {
    return html`<div class="uic-tree" role="tree">
    ${this.rows.map((row) => html`
        ${row.branch ? html`
            <div class="uic-tree-row" role="treeitem" aria-expanded=${row.expanded} data-id=${row.id} @click=${this.onRowClick}><span class="uic-tree-indent">${row.indent}</span><span class="uic-tree-marker"></span><span class="uic-tree-label">${row.label}</span></div>
        ` : nothing}
        ${row.leaf ? html`
            <div class="uic-tree-row" role="treeitem" data-id=${row.id} @click=${this.onRowClick}><span class="uic-tree-indent">${row.indent}</span><span class="uic-tree-marker"></span><span class="uic-tree-label">${row.label}</span></div>
        ` : nothing}
    `)}
</div>
`;
  }
}

customElements.define(Tree.tagName, Tree);
