// GENERATED by ui_components (uic_codegen_web) from ui_components::icon. DO NOT EDIT.
import { LitElement, html } from 'lit';

import * as impl from './uic-icon.impl.js';

export class UicIcon extends LitElement {
  static tagName = 'uic-icon';

  static properties = {
    name: { type: String, reflect: true },
  };

  name = '';

  // Light DOM so the global stylesheets (Bootstrap, elements.css) apply.
  createRenderRoot(): this {
    return this;
  }

  // ExternalStyles pattern: external stylesheets target .el-uic-icon.
  connectedCallback(): void {
    super.connectedCallback();
    this.classList.add('el-uic-icon');
  }

  // Optional lifecycle hook, present in the impl partial.
  updated(changed: Map<PropertyKey, unknown>): void {
    super.updated(changed);
    impl.updated(this, changed);
  }

  render() {
    return html`<span class="uic-icon" data-tui="icon" data-qa="uic-icon" .value=${this.name} aria-hidden="true"></span>
`;
  }
}

customElements.define(UicIcon.tagName, UicIcon);
