//! Two build steps through the in-house toolchain: the npm packages declared
//! in package.json vendor into `$OUT_DIR/vendor/`, and the TypeScript
//! runtime under js/src/ compiles per module into `$OUT_DIR/js/`; the
//! loader's module table is generated from the tree, so adding a runtime
//! module is adding a file.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use web_modules::vendor::{specs_from_package_json, vendor};

/// The dependency names of the manifest, the generic presence check:
/// every vendored package carries its own package.json once extracted.
fn dependency_names(manifest: &Path) -> Vec<String> {
    let json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(manifest).expect("read package.json"))
            .expect("parse package.json");
    json.get("dependencies")
        .and_then(|dependencies| dependencies.as_object())
        .map(|dependencies| dependencies.keys().cloned().collect())
        .unwrap_or_default()
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=package.json");
    println!("cargo:rerun-if-changed=js/src");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    vendor_packages(&out);
    compile_runtime(&out);
}

fn vendor_packages(out: &Path) {
    let vendor_dir = out.join("vendor");
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR")).join("package.json");
    let names = dependency_names(&manifest);

    // Network fetch only when a package is absent: rebuilds stay offline.
    let missing = names
        .iter()
        .any(|name| !vendor_dir.join(name).join("package.json").is_file());
    if missing {
        let specs = specs_from_package_json(&manifest).expect("read package.json");
        vendor(&vendor_dir, "/vendor", &specs).expect("vendor the browser packages");
    }
    for name in &names {
        assert!(
            vendor_dir.join(name).join("package.json").is_file(),
            "vendored package missing: {name}"
        );
    }
    println!(
        "cargo:rustc-env=UIC_JS_VENDOR_ROOT={}",
        vendor_dir.display()
    );
}

fn compile_runtime(out: &Path) {
    let src_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("js/src");
    let js_out = out.join("js");
    let mut modules: Vec<(String, PathBuf)> = Vec::new();
    compile_tree(&src_root, &src_root, &js_out, &mut modules);
    modules.sort();

    // The loader's table: every compiled module under its path specifier
    // and under its extension-less stem (`lit` beside `lit.js`,
    // `@lit/reactive-element` beside its `.js`), matching both import
    // spellings in the wild.
    let mut table = String::from(
        "/// Generated by build.rs from js/src/: the runtime modules the\n\
         /// loader serves, specifier to compiled source.\n\
         pub(crate) static COMPILED_MODULES: &[(&str, &str)] = &[\n",
    );
    for (specifier, compiled) in &modules {
        let _ = writeln!(
            table,
            "    ({specifier:?}, include_str!({:?})),",
            compiled.display()
        );
        let bare = specifier.trim_end_matches(".js");
        let _ = writeln!(
            table,
            "    ({bare:?}, include_str!({:?})),",
            compiled.display()
        );
    }
    table.push_str("];\n");
    fs::write(out.join("compiled_modules.rs"), table).expect("write module table");
}

fn compile_tree(root: &Path, dir: &Path, js_out: &Path, modules: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).expect("read js/src").flatten() {
        let path = entry.path();
        if path.is_dir() {
            compile_tree(root, &path, js_out, modules);
            continue;
        }
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        if !name.ends_with(".ts") || name.ends_with(".d.ts") {
            continue;
        }
        let relative = path.strip_prefix(root).expect("under js/src");
        let specifier = relative
            .to_string_lossy()
            .trim_end_matches(".ts")
            .to_string()
            + ".js";
        let source = fs::read_to_string(&path).expect("read runtime module");
        let compiled = web_modules::typescript::compile_str(&source, relative)
            .unwrap_or_else(|err| panic!("compile {relative:?}: {err}"));
        let target = js_out.join(&specifier);
        fs::create_dir_all(target.parent().expect("module dir")).expect("create js out dir");
        fs::write(&target, compiled).expect("write compiled module");
        modules.push((specifier, target));
    }
}
