//! Turns the vendored Material Symbols SVGs in `svg/` into build artifacts:
//! always the web sprite (`material-symbols-sprite.svg`) and the icon-name
//! table; under the `raster` feature, an alpha mask per icon for the terminal
//! twin.

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let svg_dir = manifest.join("svg");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=svg");

    let mut names: Vec<String> = Vec::new();
    for entry in fs::read_dir(&svg_dir).expect("read svg dir") {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|e| e.to_str()) == Some("svg") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                names.push(stem.to_string());
            }
        }
    }
    names.sort();
    assert!(!names.is_empty(), "no SVGs in {}", svg_dir.display());

    // The sprite: one <symbol> per icon, referenced from the web by
    // <use href="…#name">. Hidden host so it paints nothing itself.
    let mut sprite =
        String::from(r#"<svg xmlns="http://www.w3.org/2000/svg" style="display:none">"#);
    for name in &names {
        let svg = fs::read_to_string(svg_dir.join(format!("{name}.svg")))
            .unwrap_or_else(|e| panic!("read {name}.svg: {e}"));
        let view_box = attr(&svg, "viewBox").unwrap_or_else(|| "0 -960 960 960".to_string());
        let inner = inner_svg(&svg);
        sprite.push_str(&format!(
            r#"<symbol id="{name}" viewBox="{view_box}">{inner}</symbol>"#
        ));
    }
    sprite.push_str("</svg>");
    fs::write(out.join("material-symbols-sprite.svg"), &sprite).expect("write sprite");

    // The name table for lib.rs.
    let list = names
        .iter()
        .map(|n| format!("{n:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    fs::write(
        out.join("icon_names.rs"),
        format!("pub static ICON_NAMES: &[&str] = &[{list}];\n"),
    )
    .expect("write names");

    // The web map: name → inline SVG, baked into a TS module the <uic-icon>
    // component injects (CSS sizes and tints it via currentColor).
    let mut ts = String::from("// GENERATED by uic_icons. DO NOT EDIT.\n");
    ts.push_str("export const ICON_SVGS: Record<string, string> = {\n");
    for name in &names {
        let svg = fs::read_to_string(svg_dir.join(format!("{name}.svg")))
            .unwrap_or_else(|e| panic!("read {name}.svg: {e}"));
        // Rust's debug format is a valid double-quoted JS/JSON string literal.
        ts.push_str(&format!("  {name:?}: {:?},\n", svg.trim()));
    }
    ts.push_str("};\n");
    fs::write(out.join("uic-icons.ts"), ts).expect("write uic-icons.ts");

    #[cfg(feature = "raster")]
    raster::generate(&svg_dir, &names, &out);
}

/// The value of an attribute in the opening `<svg>` tag.
fn attr(svg: &str, name: &str) -> Option<String> {
    let key = format!("{name}=\"");
    let start = svg.find(&key)? + key.len();
    let end = svg[start..].find('"')? + start;
    Some(svg[start..end].to_string())
}

/// The markup between the opening `<svg …>` and the closing `</svg>` — the
/// icon's paths.
fn inner_svg(svg: &str) -> &str {
    let open_end = svg.find('>').map(|i| i + 1).unwrap_or(0);
    let close = svg.rfind("</svg>").unwrap_or(svg.len());
    svg[open_end..close].trim()
}

/// Pre-rasterizes each SVG to a square alpha mask (`mask_<name>.gray`, a
/// `MASK×MASK` grid of coverage bytes) and emits `masks.rs` mapping each name
/// to its `include_bytes!`. Only the terminal build pulls this in.
#[cfg(feature = "raster")]
mod raster {
    use std::fs;
    use std::path::Path;

    /// The master mask resolution; the runtime downsamples it to the paint box.
    const MASK: u32 = 96;

    pub fn generate(svg_dir: &Path, names: &[String], out: &Path) {
        let mut table = String::from("pub static MASKS: &[(&str, &[u8])] = &[\n");
        for name in names {
            let svg = fs::read_to_string(svg_dir.join(format!("{name}.svg")))
                .unwrap_or_else(|e| panic!("read {name}.svg: {e}"));
            let mask = rasterize(&svg);
            let file = format!("mask_{name}.gray");
            fs::write(out.join(&file), &mask).expect("write mask");
            table.push_str(&format!(
                "    ({name:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}\"))),\n"
            ));
        }
        table.push_str("];\n");
        table.push_str(&format!("pub const MASK: usize = {MASK};\n"));
        fs::write(out.join("masks.rs"), table).expect("write masks.rs");
    }

    /// Render the SVG centered in a MASK×MASK box; return the alpha channel.
    fn rasterize(svg: &str) -> Vec<u8> {
        let opt = resvg::usvg::Options::default();
        let tree = resvg::usvg::Tree::from_str(svg, &opt).expect("parse svg");
        let size = tree.size();
        let scale = MASK as f32 / size.width().max(size.height());
        let dx = (MASK as f32 - size.width() * scale) / 2.0;
        let dy = (MASK as f32 - size.height() * scale) / 2.0;
        let mut pixmap = resvg::tiny_skia::Pixmap::new(MASK, MASK).expect("pixmap");
        let transform = resvg::tiny_skia::Transform::from_row(scale, 0.0, 0.0, scale, dx, dy);
        resvg::render(&tree, transform, &mut pixmap.as_mut());
        // Coverage = the alpha channel (Material paths are opaque on transparent).
        pixmap.data().chunks_exact(4).map(|px| px[3]).collect()
    }
}
