//! Terminal rasterization: downsample an icon's build-time alpha mask to
//! Braille cells (2×4 subpixels per cell), cached per `(name, cols, rows)`.
//!
//! Colour is a paint-time concern (the caller styles the cells in the theme
//! foreground), so it is intentionally not part of the geometry cache.

use std::cell::RefCell;
use std::collections::HashMap;

// `MASKS: &[(&str, &[u8])]` (name → MASK×MASK coverage bytes) and
// `pub const MASK: usize`, generated by build.rs under the `raster` feature.
include!(concat!(env!("OUT_DIR"), "/masks.rs"));

thread_local! {
    static CACHE: RefCell<HashMap<(String, u16, u16), Vec<String>>> = RefCell::new(HashMap::new());
}

/// The Braille lines for `name` rendered into a `cols × rows` cell box, cached.
/// An unknown icon (or a zero box) yields no lines.
pub fn braille(name: &str, cols: u16, rows: u16) -> Vec<String> {
    if cols == 0 || rows == 0 {
        return Vec::new();
    }
    let key = (name.to_string(), cols, rows);
    CACHE.with(|cache| {
        if let Some(hit) = cache.borrow().get(&key) {
            return hit.clone();
        }
        let lines = render(name, cols, rows);
        cache.borrow_mut().insert(key, lines.clone());
        lines
    })
}

fn mask_for(name: &str) -> Option<&'static [u8]> {
    MASKS.iter().find(|(n, _)| *n == name).map(|(_, m)| *m)
}

/// Box-average the MASK×MASK coverage into a `(cols*2) × (rows*4)` subpixel
/// grid, threshold, and assemble U+2800 Braille glyphs.
fn render(name: &str, cols: u16, rows: u16) -> Vec<String> {
    let Some(mask) = mask_for(name) else {
        return Vec::new();
    };
    let sw = cols as usize * 2; // subpixel columns
    let sh = rows as usize * 4; // subpixel rows
    let mut on = vec![false; sw * sh];
    for sy in 0..sh {
        for sx in 0..sw {
            let x0 = sx * MASK / sw;
            let x1 = ((sx + 1) * MASK / sw).max(x0 + 1).min(MASK);
            let y0 = sy * MASK / sh;
            let y1 = ((sy + 1) * MASK / sh).max(y0 + 1).min(MASK);
            let (mut sum, mut n) = (0u32, 0u32);
            for my in y0..y1 {
                for mx in x0..x1 {
                    sum += mask[my * MASK + mx] as u32;
                    n += 1;
                }
            }
            // ~38% average coverage lights the subpixel.
            on[sy * sw + sx] = n > 0 && sum / n > 96;
        }
    }
    // Braille dot bits within a 2×4 cell, indexed [row][col].
    const BITS: [[u8; 2]; 4] = [[0x01, 0x08], [0x02, 0x10], [0x04, 0x20], [0x40, 0x80]];
    let mut lines = Vec::with_capacity(rows as usize);
    for cr in 0..rows as usize {
        let mut line = String::with_capacity(cols as usize);
        for cc in 0..cols as usize {
            let mut bits = 0u8;
            for dy in 0..4 {
                for dx in 0..2 {
                    if on[(cr * 4 + dy) * sw + (cc * 2 + dx)] {
                        bits |= BITS[dy][dx];
                    }
                }
            }
            line.push(char::from_u32(0x2800 + bits as u32).unwrap_or(' '));
        }
        lines.push(line);
    }
    lines
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_known_icon_fills_the_requested_box() {
        let lines = braille("visibility", 8, 4);
        assert_eq!(lines.len(), 4, "one string per cell row");
        assert!(lines.iter().all(|l| l.chars().count() == 8), "cols per row");
        // The eye is not blank: at least some Braille dots are lit.
        assert!(
            lines.iter().any(|l| l.chars().any(|c| c != '\u{2800}')),
            "the rasterized eye lights some cells:\n{}",
            lines.join("\n")
        );
    }

    #[test]
    fn an_unknown_icon_is_blank() {
        assert!(braille("no_such_icon", 8, 4).is_empty());
    }
}
